-- Generated by Oracle SQL Developer Data Modeler 24.3.1.347.1153
--   at:        2025-09-01 11:25:21 MSK
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE 368VD_DEPARTMAN (
	naziv_d			  VARCHAR(15) NOT NULL,
    tip_d				  VARCHAR(15) NOT NULL,
    datum_pos         DATE NOT NULL,
    manager_zap_mbr_z INTEGER NOT NULL
);

ALTER TABLE 368VD_DEPARTMAN ADD CONSTRAINT departman_pk PRIMARY KEY ( manager_zap_mbr_z );

CREATE TABLE 368VD_MANAGER (
    zap_mbr_z INTEGER NOT NULL,
    plata     INTEGER NOT NULL
);

ALTER TABLE 368VD_MANAGER ADD CONSTRAINT manager_pk PRIMARY KEY ( zap_mbr_z );

CREATE TABLE 368VD_PROJEKAT (
	naziv_p			VARCHAR(15) NOT NULL,
    sifra_p         INTEGER NOT NULL AUTO_INCREMENT,
    departman_mbr_z INTEGER NOT NULL,
	PRIMARY KEY ( sifra_p )
);

-- ALTER TABLE 368VD_PROJEKAT ADD CONSTRAINT projekat_pk PRIMARY KEY ( sifra_p );

CREATE TABLE 368VD_RADI_NA (
    radnik_zap_mbr_z INTEGER NOT NULL,
    projekat_sifra_p INTEGER NOT NULL,
    brcasova         INTEGER NOT NULL
);

ALTER TABLE 368VD_RADI_NA ADD CONSTRAINT radi_na_pk PRIMARY KEY ( radnik_zap_mbr_z,
                                                                    projekat_sifra_p );

CREATE TABLE 368VD_RADNIK (
    zap_mbr_z INTEGER NOT NULL,
    staz      INTEGER NOT NULL
);

ALTER TABLE 368VD_RADNIK ADD CONSTRAINT radnik_pk PRIMARY KEY ( zap_mbr_z );

CREATE TABLE 368VD_ZAPOSLENI (
    zap_mbr_z   INTEGER NOT NULL,
    zap_ime     VARCHAR(15) NOT NULL,
    zap_prezime VARCHAR(15) NOT NULL
);

ALTER TABLE 368VD_ZAPOSLENI ADD CONSTRAINT zaposleni_pk PRIMARY KEY ( zap_mbr_z );

ALTER TABLE 368VD_DEPARTMAN
    ADD CONSTRAINT departman_manager_fk FOREIGN KEY ( manager_zap_mbr_z )
        REFERENCES 368VD_MANAGER ( zap_mbr_z );

ALTER TABLE 368VD_MANAGER
    ADD CONSTRAINT manager_zaposleni_fk FOREIGN KEY ( zap_mbr_z )
        REFERENCES 368VD_ZAPOSLENI ( zap_mbr_z );

ALTER TABLE 368VD_PROJEKAT
    ADD CONSTRAINT projekat_departman_fk FOREIGN KEY ( departman_mbr_z )
        REFERENCES 368VD_DEPARTMAN ( manager_zap_mbr_z );

ALTER TABLE 368VD_RADI_NA
    ADD CONSTRAINT radi_na_projekat_fk FOREIGN KEY ( projekat_sifra_p )
        REFERENCES 368VD_PROJEKAT ( sifra_p );

ALTER TABLE 368VD_RADI_NA
    ADD CONSTRAINT radi_na_radnik_fk FOREIGN KEY ( radnik_zap_mbr_z )
        REFERENCES 368VD_RADNIK ( zap_mbr_z );

ALTER TABLE 368VD_RADNIK
    ADD CONSTRAINT radnik_zaposleni_fk FOREIGN KEY ( zap_mbr_z )
        REFERENCES 368VD_ZAPOSLENI ( zap_mbr_z );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
